export type Option = {
  id:number;
  first_name: string;
  last_name: string;
  gender: string;
  age: number;
  selected: boolean;
};
export const Options: Option[] = [
  {
    id:1,
    first_name: "Justin",
    last_name: "Bailey",
    gender: "Male",
    age: 18,
    selected: true,
  },
  {
    id:2,
    first_name: "Amanda",
    last_name: "Fowler",
    gender: "Female",
    age: 22,
    selected: false,
  },
  {
    id:3,
    first_name: "Steven",
    last_name: "Anderson",
    gender: "Male",
    age: 29,
    selected: false,
  },
  {
    id:4,
    first_name: "Edgar",
    last_name: "Anderson",
    gender: "Male",
    age: 28,
    selected: false,
  },
  {
    id:5,
    first_name: "Miley",
    last_name: "Thomas",
    gender: "Female",
    age: 29,
    selected: false,
  },
  {
    id:6,
    first_name: "Cherry",
    last_name: "Fowler",
    gender: "Female",
    age: 25,
    selected: false,
  },
  {
    id:7,
    first_name: "Elian",
    last_name: "Stewart",
    gender: "Male",
    age: 29,
    selected: false,
  },
  {
    id:8,
    first_name: "Deanna",
    last_name: "Foster",
    gender: "Female",
    age: 18,
    selected: false,
  },
  {
    id:9,
    first_name: "Ada",
    last_name: "Grant",
    gender: "Female",
    age: 23,
    selected: false,
  },
  {
    id:10,
    first_name: "Arianna",
    last_name: "West",
    gender: "Female",
    age: 29,
    selected: false,
  },
  {
    id:11,
    first_name: "Leonardo",
    last_name: "Jones",
    gender: "Male",
    age: 28,
    selected: false,
  },
  {
    id:12,
    first_name: "Maddie",
    last_name: "Hill",
    gender: "Female",
    age: 24,
    selected: false,
  },
  {
    id:13,
    first_name: "Owen",
    last_name: "Miller",
    gender: "Male",
    age: 27,
    selected: false,
  },
  {id:14,
    first_name: "Arianna",
    last_name: "Harrison",
    gender: "Female",
    age: 29,
    selected: false,
  },
  {id:15,
    first_name: "Jared",
    last_name: "Fowler",
    gender: "Male",
    age: 22,
    selected: false,
  },
  {id:16,
    first_name: "Annabella",
    last_name: "Carroll",
    gender: "Female",
    age: 24,
    selected: false,
  },
  {id:17,
    first_name: "Arianna",
    last_name: "Howard",
    gender: "Female",
    age: 25,
    selected: false,
  },
  {id:18,
    first_name: "Carlos",
    last_name: "Allen",
    gender: "Male",
    age: 20,
    selected: false,
  },
  {id:19,
    first_name: "Walter",
    last_name: "Morgan",
    gender: "Male",
    age: 19,
    selected: false,
  },
  {id:20,
    first_name: "Sofia",
    last_name: "Perry",
    gender: "Female",
    age: 29,
    selected: false,
  },
  {id:21,
    first_name: "Alford",
    last_name: "Perkins",
    gender: "Male",
    age: 30,
    selected: false,
  },
  {id:22,
    first_name: "Audrey",
    last_name: "Ferguson",
    gender: "Female",
    age: 20,
    selected: false,
  },
  {id:23,
    first_name: "Connie",
    last_name: "Harper",
    gender: "Female",
    age: 23,
    selected: false,
  },
  {id:24,
    first_name: "Lucy",
    last_name: "Owens",
    gender: "Female",
    age: 27,
    selected: false,
  },
  {id:25,
    first_name: "Maximilian",
    last_name: "Douglas",
    gender: "Male",
    age: 23,
    selected: false,
  },
  {id:26,
    first_name: "Anna",
    last_name: "Hawkins",
    gender: "Female",
    age: 23,
    selected: false,
  },
  {id:27,
    first_name: "Kristian",
    last_name: "Davis",
    gender: "Male",
    age: 28,
    selected: false,
  },
  {id:28,
    first_name: "Adison",
    last_name: "Ross",
    gender: "Male",
    age: 21,
    selected: false,
  },
  {id:29,
    first_name: "Elise",
    last_name: "Craig",
    gender: "Female",
    age: 29,
    selected: false,
  },
  {id:30,
    first_name: "Abigail",
    last_name: "Davis",
    gender: "Female",
    age: 25,
    selected: false,
  },
];
